name: neurovision_platform
description: "NeuroVision - Assistive Learning Platform for ADHD, Dyslexia & Visually Impaired users."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # --- Core ---
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1

  # --- Vision Module: ML Kit & Camera ---
  google_mlkit_object_detection: ^0.13.0
  google_mlkit_image_labeling: ^0.11.0
  camera: ^0.11.1+2

  # --- Vision Module: Haptic & Audio Feedback ---
  vibration: ^2.0.0
  flutter_tts: ^4.2.0

  # --- Accessibility ---
  google_fonts: ^6.2.1
  flutter_vision: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/labels/
    - assets/models/
